version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: some-mysql
    networks:
      - prestashop-net
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"

  prestashop:
    image: prestashop/prestashop
    container_name: some-prestashop
    networks:
      - prestashop-net
    environment:
      DB_SERVER: some-mysql
    ports:
      - "8080:80"

networks:
  prestashop-net: